import * as FaIcons from "react-icons/fa";

const timeTables_Time = [
  { time: "10:05 - 10:50" },
  { time: "10:50 - 11:35" },
  { time: "11:35 - 12:20" },
  { time: "12:20 - 1:05" },
  { time: "1:05 - 1:50" },
  { time: "1:50 - 2:35" },
  { time: "2:35 - 3:20" },
  { time: "3:20 - 4:05" },
  { time: "4:05 - 4:50" },
];

const timeTable_value = [
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Monday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Tuesday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Wednesday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Thursday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Friday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
  {
    day: "Sunday",
    time: "10:05 - 10:50",
    classes: 12,
    section: "A",
    subject: "Math",
    teacher: "Prabin Gautam",
  },
];

const addSlot = [
  {
    title: "Day",
    input: "dropdown",
    icon: <FaIcons.FaUser className="mid-icon" />,
    placeholder: "Day",
    name: "scheduleDay",
    isRequired: true,
    options: [
      { value: "Sunday", label: "Sunday" },
      { value: "Monday", label: "Monday" },
      { value: "Tuesday", label: "Tuesday" },
      { value: "Wednesday", label: "Wedday" },
      { value: "Thursday", label: "Thursday" },
      { value: "Friday", label: "Friday" },
    ],
  },
  {
    title: "Start Time",
    input: "time",
    icon: <FaIcons.FaUser className="mid-icon" />,
    placeholder: "Start Time",
    name: "scheduleStartTime",
    isRequired: true,
  },
  {
    title: "EndTime",
    input: "time",
    icon: <FaIcons.FaUser className="mid-icon" />,
    placeholder: "End Time",
    name: "scheduleEndTime",
    isRequired: true,
  },

  {
    title: "Class",
    input: "dropdown",
    icon: <FaIcons.FaCode className="mid-icon" />,
    isRequired: true,
    name: "scheduleClassName",
    options: [
      { value: "5", label: "5" },
      { value: "6", label: "6" },
      { value: "7", label: "7" },
      { value: "8", label: "8" },
      { value: "9", label: "9" },
      { value: "10", label: "10" },
      { value: "11", label: "11" },
      { value: "12", label: "12" },
    ],
  },
  {
    title: "Section",
    input: "dropdown",
    icon: <FaIcons.FaCode className="mid-icon" />,
    isRequired: false,
    name: "scheduleSection",
    options: [
      { value: "A", label: "A" },
      { value: "B", label: "B" },
      { value: "C", label: "C" },
    ],
  },
  {
    title: "Subject",
    input: "text",
    icon: <FaIcons.FaUser className="mid-icon" />,
    placeholder: "Enter Subject",
    name: "scheduleSubject",
    isRequired: true,
  },
  {
    title: "Teacher",
    input: "dropdown",
    icon: <FaIcons.FaUser className="mid-icon" />,
    placeholder: "Assign Teacher",
    name: "scheduleTeacher",
    isRequired: true,
    options: [
      { value: "Kushal Pangeni", label: "Kushal Pangeni" },
      { value: "Mishan Khatri", label: "Mishan Khatri" },
      { value: "Paras Panta", label: "Paras Panta" },
      { value: "Prabin Gautam", label: "Prabin Gautam" },
    ],
  },
];

export { timeTables_Time, addSlot, timeTable_value };
