export const GET_TEACHER_DETAIL = "GET_TEACHER_DETAIL";
export const UPDATE_TEACHER_DETAIL = "UPDATE_TEACHER_DETAIL ";
export const GET_TEACHER_CLASS = "GET_TEACHER_CLASS";
export const ADD_TEACHER_DETAIL = "ADD_TEACHER_DETAIL";
