export const GET_TEACHER_DETAIL = "GET_TEACHER_DETAIL";
export const UPDATE_TEACHER_DETAIL = "UPDATE_TEACHER_DETAIL ";
export const GET_TEACHER_CLASS = "GET_TEACHER_CLASS";
export const ADD_TEACHER_DETAIL = "ADD_TEACHER_DETAIL";
export const DELETE_TEACHER_DETAIL = "DELETE_TEACHER_DETAIL";

export const GET_TEACHER_BYID = "GET_TEACHER_BYID";

//Lecture notes
export const GET_LECTURE_NOTES = "GET_LECTURE_NOTES";
export const DELETE_LECTURE_NOTES = "DELETE_LECTURE_NOTES";

//Assignmenet
export const GET_TEACHER_GIVEN_ASSIGNMENT = "GET_TEACHER_GIVEN_ASSIGNMENT";
export const GET_TEACHER_ASSIGNMENT_BYID = "GET_TEACHER_ASSIGNMENT_BYID";
export const DELETE_TEACHER_GIVEN_ASSIGNMENT =
  "DELETE_TEACHER_GIVEN_ASSIGNMENT";
