export const VIEW_SUBJECTS = "VIEW_SUBJECTS";
export const VIEW_SUBJECTS_ID = "VIEW_SUBJECTS_ID";
export const DELETE_SUBJECTS = "DELETE_SUBJECTS";
export const ADD_SUBJECT = "ADD_SUBJECT";

export const UPDATE_SUBJECT_DETAIL = "UPDATE_SUBJECT_DETAIL";
