export const GET_STUDENT_DETAIL = "GET_STUDENT_DETAIL";
export const GET_STUDENTCLASS_SID = "GET_STUDENTCLASS_SID";
export const UPDATE_STUDENT_DETAIL = "UPDATE_STUDENT_DETAIL ";
export const GET_STUDENT_CLASS = "GET_STUDENT_CLASS";
export const GET_STUDENT_PARENTS = "GET_STUDENT_PARENTS";
export const DELETE_STUDENT = "DELETE_STUDENT";

export const GET_STUDENT_ATTENDANCE = "GET_STUDENT_ATTENDANCE";
export const DELETE_ATTENDANCE = "DELETE_ATTENDANCE";
