# Generated by Django 4.0.1 on 2022-02-03 08:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_users',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to=users.models.upload_to),
        ),
    ]
