# Generated by Django 4.0.1 on 2022-02-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cms_users_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cms_users',
            name='fullname',
        ),
    ]
