# Generated by Django 4.0.1 on 2022-02-09 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateField()),
                ('time_due', models.TimeField()),
                ('related_files', models.FileField(blank=True, null=True, upload_to='given_assignments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='adminannouncement',
            name='files_by_admin',
            field=models.FileField(blank=True, null=True, upload_to='admin_announcements'),
        ),
        migrations.AddField(
            model_name='adminannouncement',
            name='type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Admininstration', 'Admininstration'), ('Admission', 'Admission'), ('Other', 'Other')], default='Academic', max_length=50),
        ),
        migrations.CreateModel(
            name='TeachersAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files_by_teachers', models.FileField(blank=True, null=True, upload_to='teacher_announcements')),
                ('announcement_for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_announcements', to='core.grade')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRN', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('DOB', models.DateField(default='2000-01-01')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default.png', upload_to='teachers_profile_pics')),
                ('contact_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_files', models.FileField(blank=True, null=True, upload_to='submitted_assignments')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='core.givenassignments')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=55)),
                ('subject_code', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='core.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRN', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('DOB', models.DateField(default='2000-01-01')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default.png', upload_to='student_profile_pics')),
                ('contact_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50)),
                ('current_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('parent_address', models.CharField(max_length=100)),
                ('parent_state', models.CharField(max_length=100)),
                ('parent_contact_no', models.IntegerField()),
                ('parent_additional_contact_no', models.IntegerField(blank=True)),
                ('parent_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_info', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='LectureNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('notes_files', models.FileField(blank=True, null=True, upload_to='lecture_notes')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_notes', to='core.subject')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='section',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='core.section'),
        ),
        migrations.AddField(
            model_name='givenassignments',
            name='for_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_grades', to='core.grade'),
        ),
        migrations.AddField(
            model_name='givenassignments',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.subject'),
        ),
        migrations.CreateModel(
            name='AssignTeacherToSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_grade', to='core.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_assigned', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_assigned_subjects', to='core.teacher')),
            ],
        ),
    ]
