# Generated by Django 4.0.1 on 2022-02-03 08:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminannouncement',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
    ]
