# Generated by Django 4.0.1 on 2022-02-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_givenassignments_grade_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='gender',
        ),
    ]
