# Generated by Django 4.0.1 on 2022-02-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_givenassignments_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminannouncement',
            name='type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Admistration', 'Admistration'), ('Admission', 'Admission'), ('Other', 'Other')], default='Academic', max_length=50),
        ),
    ]
