# Generated by Django 4.0.1 on 2022-02-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
        migrations.AlterField(
            model_name='lecturenotes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_name', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_additional_contact_no',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='DOB',
            field=models.DateField(default='1998-01-01'),
        ),
    ]
