# Generated by Django 4.0.1 on 2022-02-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_photo_alter_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ROLL',
            field=models.IntegerField(null=True),
        ),
    ]
