# Generated by Django 4.0.1 on 2022-02-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ROLL',
        ),
    ]
