# Generated by Django 4.0.1 on 2022-02-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_additional_contact_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
