# Generated by Django 4.0.1 on 2022-02-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_parent_parent_additional_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email address'),
        ),
    ]
